# Generated by Django 3.2.18 on 2023-05-22 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('popularity', models.FloatField()),
                ('video_id', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.CharField(blank=True, max_length=100)),
                ('runtime', models.CharField(max_length=50)),
                ('backdrop_path', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('adult', models.TextField(blank=True)),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
